name: Publish docs
inputs:
  build-tasks:
    description: 'Tasks to run for the gradle build, can have multiple space separated tasks'
    required: false
    default: 'docsGenerate'
  outputDir:
    description: 'Output directory of generated docs'
    required: false
    default: 'out'
  update-subdomain-links:
    description: 'Whether to update links pointing to / to a subdomain (defaulting to the repo name)'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - uses: MineInAbyss/publish-action@v3
      with:
        publish-github-release: false
        build-tasks: ${{ inputs.build-tasks }}

    - name: Update HTML links for GitHub Pages subdomain
      run: |
        find '${{ inputs.outputDir }}' -name "*.html" -exec sed -i 's#href="/#href="/${{ github.event.repository.name }}/#g; s#src="/#src="/${{ github.event.repository.name }}/#g' {} \;
      shell: bash
      if: "${{ inputs.update-subdomain-links == 'true' }}"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.outputDir }}
